-- Runs a Lua chunk generated by StageLogic against a mocked Hyprland API, so
-- the exact string the compositor would execute is what gets tested.
--
--   lua tests/chunk.lua <world> < chunk
--
-- Prints one line: the chunk's return tag, then every dispatch it made. The
-- assertions live in the node test files that generate the chunks.
--
-- The mock mirrors Hyprland 0.56.2, verified live: windows are userdata-like
-- objects with `address` (a "0x…" string), `at`/`size` tables of x/y,
-- `mapped`/`hidden`/`floating` booleans, `fullscreen`/`fullscreen_client`
-- integers, `group` (nil when ungrouped), and `workspace`/`monitor` objects
-- with an `id`. `hl.get_workspace` answers nil for a workspace that does not
-- exist and never creates one. `existing` is the set of workspaces the
-- compositor has, which is not the same thing as the list Stage is showing.

local function win(t)
  return {
    address = t.address,
    at = { x = t.x, y = t.y },
    size = { x = t.w, y = t.h },
    mapped = t.mapped ~= false,
    hidden = t.hidden == true,
    floating = t.floating == true,
    fullscreen = t.fullscreen or 0,
    fullscreen_client = t.fullscreen_client or 0,
    group = t.group,
    workspace = { id = t.ws or 1 },
    monitor = { id = t.mon or 1 },
  }
end

-- A 2x2 tiling on workspace 1 plus one window each on 3 and 7, the live
-- fixture layout: a top-left, b top-right, c bottom-left, d bottom-right.
local function tiled()
  return {
    win{ address = "0xa", x = 0,   y = 0,   w = 800, h = 500 },
    win{ address = "0xb", x = 800, y = 0,   w = 800, h = 500 },
    win{ address = "0xc", x = 0,   y = 500, w = 800, h = 500 },
    win{ address = "0xd", x = 800, y = 500, w = 800, h = 500 },
    win{ address = "0xe", x = 0,   y = 0,   w = 1600, h = 1000, ws = 3 },
    win{ address = "0xf", x = 0,   y = 0,   w = 1600, h = 1000, ws = 7 },
  }
end

-- Each unsupported source is 0xa, with an ordinary window to its right.
local function alone(overrides)
  overrides.address = "0xa"
  overrides.x, overrides.y, overrides.w, overrides.h = 0, 0, 800, 500
  return { win(overrides), win{ address = "0xb", x = 800, y = 0, w = 800, h = 500 } }
end

local WORLDS = {
  tiled = { windows = tiled(), existing = { 1, 3, 7 } },

  grouped = { windows = alone{ group = { "0xb" } }, existing = { 1, 3, 7 } },
  -- Not tiled. A swap rearranges a tiling and refuses all three; the move
  -- chunk never looks at any of these fields, so it moves them.
  floating = { windows = alone{ floating = true }, existing = { 1, 3, 7 } },
  fullscreen = { windows = alone{ fullscreen = 2 }, existing = { 1, 3, 7 } },
  fullscreenclient = { windows = alone{ fullscreen_client = 1 }, existing = { 1, 3, 7 } },
  unmapped = { windows = alone{ mapped = false }, existing = { 1, 3, 7 } },
  hiddensource = { windows = alone{ hidden = true }, existing = { 1, 3, 7 } },

  -- Nothing shares a span with the source on either axis.
  diagonal = { windows = {
    win{ address = "0xa", x = 0,   y = 0,   w = 400, h = 300 },
    win{ address = "0xb", x = 500, y = 400, w = 400, h = 300 },
  }, existing = { 1, 3, 7 } },

  -- Unsupported and foreign candidates are skipped, not swapped with: to the
  -- right of 0xa sit a floating, a grouped and a fullscreen window and one on
  -- another monitor, then an ordinary window further out.
  candidates = { windows = {
    win{ address = "0xa", x = 0,    y = 0, w = 400, h = 500 },
    win{ address = "0xb", x = 400,  y = 0, w = 400, h = 500, floating = true },
    win{ address = "0xc", x = 800,  y = 0, w = 400, h = 500, group = { "0xa" } },
    win{ address = "0xd", x = 1200, y = 0, w = 400, h = 500, fullscreen = 2 },
    win{ address = "0xe", x = 1600, y = 0, w = 400, h = 500, mon = 2 },
    win{ address = "0xf", x = 2000, y = 0, w = 400, h = 500 },
  }, existing = { 1, 3, 7 } },

  -- Two candidates at the same distance and the same perpendicular offset:
  -- the lower address wins, so the choice never depends on enumeration order.
  duplicates = { windows = {
    win{ address = "0xa", x = 0,   y = 0, w = 400, h = 400 },
    win{ address = "0xc", x = 400, y = 0, w = 400, h = 400 },
    win{ address = "0xb", x = 400, y = 0, w = 400, h = 400 },
  }, existing = { 1, 3, 7 } },

  -- Two equally distant candidates: the nearer perpendicular centre wins.
  ties = { windows = {
    win{ address = "0xa", x = 0,   y = 200, w = 400, h = 400 },
    win{ address = "0xb", x = 400, y = 0,   w = 400, h = 400 },
    win{ address = "0xc", x = 400, y = 400, w = 400, h = 300 },
  }, existing = { 1, 3, 7 } },

  -- The window has moved since Stage drew it: it is not on the workspace the
  -- chunk was built for.
  stale = { windows = { win{ address = "0xa", x = 0, y = 0, w = 800, h = 500, ws = 5 },
                        win{ address = "0xb", x = 800, y = 0, w = 800, h = 500, ws = 5 } },
    existing = { 1, 3, 7 } },

  -- The destination exists but on another monitor.
  foreignmonitor = { windows = tiled(),
    existing = { 1, 3, 7 }, monitors = { [3] = 2 } },

  -- Workspace 3 does not exist yet: the move creates it, which is what the
  -- grid's "+" slot asks for.
  missing = { windows = tiled(), existing = { 1, 7 } },

  -- The window vanished between Stage drawing it and the chunk running.
  gone = { windows = {}, existing = { 1, 3, 7 } },
}

local world = WORLDS[arg[1]] or error("unknown world: " .. tostring(arg[1]))
local dispatched = {}

local function selected(sel)
  local address = tostring(sel):match("^address:(.+)$")
  for _, w in ipairs(world.windows) do
    if w.address == address then return w end
  end
  return nil
end

local function describe(args)
  local keys = {}
  for k in pairs(args) do keys[#keys + 1] = k end
  table.sort(keys)
  local parts = {}
  for _, k in ipairs(keys) do
    parts[#parts + 1] = k .. "=" .. tostring(args[k])
  end
  return table.concat(parts, ",")
end

hl = {
  get_window = selected,

  get_windows = function(filters)
    local out = {}
    for _, w in ipairs(world.windows) do
      local keep = true
      if filters.workspace ~= nil and filters.workspace.id ~= w.workspace.id then
        keep = false
      end
      if filters.monitor ~= nil and filters.monitor.id ~= w.monitor.id then
        keep = false
      end
      if keep then out[#out + 1] = w end
    end
    return out
  end,

  get_workspace = function(sel)
    local id = tonumber(sel)
    for _, existing in ipairs(world.existing) do
      if existing == id then
        return { id = id, monitor = { id = (world.monitors or {})[id] or 1 } }
      end
    end
    return nil
  end,

  -- Where the pointer is, so a swap can put it back after Hyprland's own
  -- warp. A fixed position is enough: the chunk only has to restore it.
  get_cursor_pos = function() return { x = 640, y = 480 } end,

  dsp = {
    window = {
      move = function(args) return "move{" .. describe(args) .. "}" end,
      swap = function(args) return "swap{" .. describe(args) .. "}" end,
    },
    cursor = {
      move = function(args) return "cursor{" .. describe(args) .. "}" end,
    },
  },

  dispatch = function(command) dispatched[#dispatched + 1] = command end,
}

local chunk = assert(load("return " .. io.read("*a"), "StageLogic"))()
local tag = chunk()
print(tostring(tag) .. " " .. table.concat(dispatched, " "))
